package tw.com.eeit.ajax.ch3.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import tw.com.eeit.ajax.ch1.model.User; // Reuse Ch1 model for simplicity, or create new Ch3 model
import tw.com.eeit.ajax.ch3.dto.UserCreateRequest;
import tw.com.eeit.ajax.ch3.dto.UserResponse;

@Mapper(componentModel = "spring")
public interface UserMapper {

    // Entity to DTO
    @Mapping(target = "username", source = "name") // Ch1 User model has 'name', DTO has 'username'
    UserResponse toDto(User user);

    // DTO to Entity
    @Mapping(target = "name", source = "username")
    @Mapping(target = "id", ignore = true) // ID generated by DB
    @Mapping(target = "skills", ignore = true)
    @Mapping(target = "secret", ignore = true)
    User toEntity(UserCreateRequest request);
}
